// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAMS.Database;

#nullable disable

namespace PAMS.Migrations
{
    [DbContext(typeof(Mycontext))]
    partial class MycontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PAMS.Models.All_departments", b =>
                {
                    b.Property<int>("Department_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Department_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Department_Id");

                    b.ToTable("All_departments");
                });

            modelBuilder.Entity("PAMS.Models.All_positions", b =>
                {
                    b.Property<int>("Position_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Position_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Position_Id");

                    b.ToTable("All_positions");
                });

            modelBuilder.Entity("PAMS.Models.All_users", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("User_Position_id")
                        .HasColumnType("int");

                    b.Property<string>("User_Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("User_department_id")
                        .HasColumnType("int");

                    b.Property<string>("User_email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("User_pass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("User_id");

                    b.HasIndex("User_Position_id");

                    b.HasIndex("User_department_id");

                    b.ToTable("All_users");
                });

            modelBuilder.Entity("PAMS.Models.All_users", b =>
                {
                    b.HasOne("PAMS.Models.All_positions", "Positions")
                        .WithMany("Users")
                        .HasForeignKey("User_Position_id");

                    b.HasOne("PAMS.Models.All_departments", "Departments")
                        .WithMany("Users")
                        .HasForeignKey("User_department_id");

                    b.Navigation("Departments");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("PAMS.Models.All_departments", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PAMS.Models.All_positions", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
